import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { roboto } from "./ui/fonts";
import NextAuthSession from "./NextAuthSession";
import { UIProviders } from "./providers/layout-ui";

//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
// const geistSans = Geist({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Laporan Bencana",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.className} antialiased`}>
        <NextAuthSession>
          <UIProviders>{children}</UIProviders>
        </NextAuthSession>
      </body>
    </html>
  );
}
